//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_GEN_Area_Master
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string NameEng { get; set; }
        public string ShortEng { get; set; }
        public string NameAra { get; set; }
        public string ShortAra { get; set; }
        public bool IsDefault { get; set; }
        public int StatusTypeId { get; set; }
        public int ActionUserId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int ApprvTypeId { get; set; }
        public int ApprvUserId { get; set; }
        public System.DateTime ApprvDate { get; set; }
    }
}
