//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_ORG_Company_Master
    {
        public int Id { get; set; }
        public int DivisionId { get; set; }
        public string NameEng { get; set; }
        public string ShortEng { get; set; }
        public string NameAra { get; set; }
        public string ShortAra { get; set; }
        public byte[] Logo { get; set; }
        public bool IsDefault { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Addres { get; set; }
        public string Landmark { get; set; }
        public string POBox { get; set; }
        public int AreaId { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
        public int RegionId { get; set; }
        public int CountryId { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public int ActionUserId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int ApprvTypeId { get; set; }
        public Nullable<int> ApprvUserId { get; set; }
        public System.DateTime ApprvDate { get; set; }
    }
}
