//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_ACC_COA_Master
    {
        public Nullable<int> AccountId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string AccountNo { get; set; }
        public string NameEng { get; set; }
        public string NameAra { get; set; }
        public int TypeId { get; set; }
        public int GroupNo { get; set; }
        public int GroupId { get; set; }
        public int LevelNo { get; set; }
        public string GrpFlag { get; set; }
        public string BalSign { get; set; }
        public string ActionUserId { get; set; }
        public System.DateTime ActionDate { get; set; }
    }
}
