//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_SAM_Salesman_Master
    {
        public int EmpId { get; set; }
        public string Number { get; set; }
        public string NameEng { get; set; }
        public string ShortEng { get; set; }
        public string NameAra { get; set; }
        public string ShortAra { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string Mobile { get; set; }
        public string WhatsApp { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Email { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<int> ActionUserId { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> ApprovedTypeId { get; set; }
        public Nullable<int> ApprvUserId { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
