//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class INV_MSD_Item
    {
        [Key]
        public long Id { get; set; }
        public string ItemCode { get; set; }
        public string NameEng { get; set; }
        public string ShortEng { get; set; }
        [Column(TypeName = "nvarchar(1000)")]
        public string NameAra { get; set; }
        [Column(TypeName = "nvarchar(300)")]
        public string ShortAra { get; set; }
        public Nullable<bool> IsDeafult { get; set; }
        public Nullable<int> Rating { get; set; }
        public string PackiseSize { get; set; }
        public Nullable<bool> IsExpiration { get; set; }
        public string ExpiryDays { get; set; }
        public string ReminderDays { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> SubCatId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> PackingSizeID { get; set; }
        public Nullable<bool> IsPerishable { get; set; }
        public Nullable<bool> IsConsignment { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public Nullable<int> StockMethodID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> EstProfitPer { get; set; }
        public Nullable<bool> IsPrintable { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.DateTime> LastActived { get; set; }
        public Nullable<System.DateTime> DraftedOn { get; set; }
        public Nullable<System.DateTime> LastDelted { get; set; }
        public Nullable<System.DateTime> LastRecall { get; set; }
        public Nullable<int> ActionUserId { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> ApprvTypeId { get; set; }
        public Nullable<int> ApprvUserId { get; set; }
        public Nullable<System.DateTime> ApprvDate { get; set; }
        public string ImageUrl { get; set; }
        public virtual ICollection<INV_MSD_SubItemCode> INV_MSD_SubItems { get; set; }
        [ForeignKey("CatId")]
        public virtual INV_MSD_Category Category { get; set; }
        public int ApprovedBy { get; set; }
    }
}
