//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class INV_MSD_SubItemCode
    {
        [Key]
        public long Id { get; set; }
        public Nullable<int> Seq { get; set; }
        public string SubItemCode { get; set; } // This should be Key []
        public string ShortEng { get; set; }
        [Column(TypeName = "nvarchar(1000)")]
        public string ShortArb { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> EstProfit { get; set; }
        public Nullable<decimal> Selling_Price { get; set; }





        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public Nullable<decimal> EpAmount { get; set; }
        public string ImageUrl { get; set; }




        public long ItemId { get; set; }
        [ForeignKey("ItemId")]
        public virtual INV_MSD_Item Item { get; set; }

        public Nullable<int> CatId { get; set; }
        [ForeignKey("CatId")]
        public virtual INV_MSD_Category Category { get; set; }

        public ICollection<SD_POS_InvoiceDetail> invoiceDetails { get; set; }


    }
}
