//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_MSD_SubItemCode_Backup
    {
        public long ItemId { get; set; }
        public Nullable<int> Seq { get; set; }
        public string SubItemCode { get; set; }
        public string ShortEng { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
