//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class INV_MSD_Model
    {
        [Key]
        public long Id { get; set; }
        public string Number { get; set; }
        public string NameEng { get; set; }
        public string ShortEng { get; set; }
        public string NameAra { get; set; }
        public string ShortAra { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> ApprvTypeId { get; set; }
        public Nullable<int> ApprovedTypeId { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }


    public partial class INV_MSD_Department
    {
        [Key]
        public long Id { get; set; }
        public string Number { get; set; }
        public string NameEng { get; set; }
        public string ShortEng { get; set; }
        public string NameAra { get; set; }
        public string ShortAra { get; set; }
        public Nullable<bool> IsDefault { get; set; } 
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<System.DateTime> Action_Date { get; set; }
        public Nullable<int> ApprvTypeId { get; set; }
        public Nullable<int> ApprvUserId { get; set; }
        public Nullable<System.DateTime> ApprvDate { get; set; }
    }



    public partial class INV_MSD_PackingSize
    {
        [Key]
        public long Id { get; set; }
        public string Number { get; set; }
        public string NameEng { get; set; }
        public string ShortEng { get; set; }
        public string NameAra { get; set; }
        public string ShortAra { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<System.DateTime> Action_Date { get; set; }
        public Nullable<int> ApprvTypeId { get; set; }
        public Nullable<int> ApprvUserId { get; set; }
        public Nullable<System.DateTime> ApprvDate { get; set; }
    }

}
