//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class INV_MSD_SubItemPrice
    {
        [Key]
        public long Id { get; set; }
        public long ItemId { get; set; }
        public string SubItemCode { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> EstProfit { get; set; }
        public Nullable<decimal> Selling_Price { get; set; }
    }
}
