//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
 
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SD_POS_Invoice  
    {
        [Key]
        public long DocumentNo { get; set; }

        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> BranchID { get; set; }
     
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<byte> DocumentTypeID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceTypeID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Void { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Round { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Card { get; set; }
        public Nullable<byte> CardTypeID { get; set; }
        public Nullable<int> Items { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> CounterNo { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public Nullable<byte> ApproveID { get; set; }
        public Nullable<short> ActionUserID { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
        public Nullable<byte> ExpTypeID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string ModeOfPayment  { get; set; }
        public virtual ICollection<SD_POS_InvoiceDetail> SD_POS_InvoiceDetail { get; set; }
    }

    public partial class SD_POS_Invoice_Template
    {
        [Key]
        public long DocumentNo { get; set; }

        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> BranchID { get; set; }

        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<byte> DocumentTypeID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceTypeID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Void { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Round { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Card { get; set; }
        public Nullable<byte> CardTypeID { get; set; }
        public Nullable<int> Items { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> CounterNo { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public Nullable<byte> ApproveID { get; set; }
        public Nullable<short> ActionUserID { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
        public Nullable<byte> ExpTypeID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public long RefDocumentNo { get; set; }
        public string ModeOfPayment { get; set; }
        public virtual ICollection<SD_POS_InvoiceDetail_Template> SD_POS_InvoiceDetail { get; set; }
    }
}
