//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SD_POS_InvoiceDetail
    {
        [Key]
        public long Id { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> BranchID { get; set; }
        public Nullable<long> DocumentNo { get; set; }
        public long ItemID { get; set; }
        public string SubitemCode { get; set; }
        public Nullable<short> Seq { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public string Status { get; set; }






        [ForeignKey("ItemID")]
        public virtual INV_MSD_SubItemCode SubItemCode { get; set; }
        public virtual SD_POS_Invoice SD_POS_Invoice { get; set; }
    }


    public partial class SD_POS_InvoiceDetail_Template
    {
        [Key]
        public long Id { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> BranchID { get; set; }
        public Nullable<long> DocumentNo { get; set; }
        public long ItemID { get; set; }
        public string SubitemCode { get; set; }
        public Nullable<short> Seq { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public string Status { get; set; }

        [ForeignKey("ItemID")]
        public virtual INV_MSD_SubItemCode SubItemCode { get; set; }
        public virtual SD_POS_Invoice_Template SD_POS_Invoice { get; set; }

    }




    public partial class SD_Purchase_InvoiceDetail
    {
        [Key]
        public long Id { get; set; }

        public long ItemID { get; set; }
        public string SubitemCode { get; set; }
        public Nullable<short> Seq { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public string Status { get; set; }
        public string ImageUrl { get; set; }

        [ForeignKey("ItemID")]
        public virtual INV_MSD_SubItemCode SubItemCode { get; set; }
        public virtual SD_POS_Invoice SD_POS_Invoice { get; set; }
    }

}
