//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_SAL_QuotationDeatil
    {
        public int DocumentId { get; set; }
        public string DocumentType { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public string QuotationNo { get; set; }
        public System.DateTime QuotationDate { get; set; }
        public int SalesmanId { get; set; }
        public int CustomerId { get; set; }
        public int InvoiceTypeId { get; set; }
        public byte DueDays { get; set; }
        public System.DateTime DueDate { get; set; }
        public int DueTermsId { get; set; }
        public string Notes { get; set; }
        public bool DiscountType { get; set; }
        public byte DiscountPercent { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TaxableAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal SubTotal { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal RoundAmount { get; set; }
        public decimal NetAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal DuesAmount { get; set; }
        public byte Total_Items { get; set; }
        public decimal TotalWeight { get; set; }
        public int ActionUserId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int ApprovedTypeId { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public int StationId { get; set; }
    }
}
