//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSERP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_SAL_Quotation
    {
        public int DocumentId { get; set; }
        public int ItemSeq { get; set; }
        public int ItemId { get; set; }
        public short Qty { get; set; }
        public int UnitId { get; set; }
        public decimal Unitprice { get; set; }
        public decimal Discount { get; set; }
        public decimal Taxable { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
        public int ActionUserId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int ApprovedTypeId { get; set; }
        public System.DateTime ApprovedDate { get; set; }
    }
}
