//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero.Application.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zero.Application.Shared.Resources.UsersResource", typeof(UsersResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id in the headers is required..
        /// </summary>
        public static string DeviceHeaderRequiredText {
            get {
                return ResourceManager.GetString("DeviceHeaderRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is blocked/inactive. Please contact Administrator for assistance..
        /// </summary>
        public static string InactiveDriverText {
            get {
                return ResourceManager.GetString("InactiveDriverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user: {0} created successfully..
        /// </summary>
        public static string NewUserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("NewUserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token is expired for the user..
        /// </summary>
        public static string RefreshTokenExpiredText {
            get {
                return ResourceManager.GetString("RefreshTokenExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login to this device. Please contact Administrator for assistance..
        /// </summary>
        public static string UnableToLoginText {
            get {
                return ResourceManager.GetString("UnableToLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the same username {0} already existed and updated successfully..
        /// </summary>
        public static string UserAlreadyExistedAndUpdated {
            get {
                return ResourceManager.GetString("UserAlreadyExistedAndUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0} deleted successfully..
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID: {0} doesn&apos;t exists..
        /// </summary>
        public static string UserDoesNotExists {
            get {
                return ResourceManager.GetString("UserDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with name {0} is not registered..
        /// </summary>
        public static string UserIsNotRegistered {
            get {
                return ResourceManager.GetString("UserIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} is already taken..
        /// </summary>
        public static string UsernameAlreadyTaken {
            get {
                return ResourceManager.GetString("UsernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string UsernamePasswordInvalidText {
            get {
                return ResourceManager.GetString("UsernamePasswordInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0} updated successfully..
        /// </summary>
        public static string UserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
